include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-raw-types: true
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - lib/l10n/**

linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_redundant_argument_values: true
    directives_ordering: true
    prefer_const_constructors: true
    prefer_final_locals: true
    public_member_api_docs: false
    sort_constructors_first: true
